### ISSUE TITLE
German Strong/Weak/Mixed Declension

### ISSUE THREAD

**Issue by joramkuntze** [unimorph/wiktionary-tools#1]
How to annotate German Strong/Weak/Mixed declension in adjectives. It seems to me that there are no available Tags.

**Comment by aryamccarthy** [comment]
Hi,

UniMorph doesn't mark these in adjectives—it's not a dimension of _meaning_, and it has no cross-lingual correlate. For motivations of the UniMorph schema, see [Sylak-Glassman, Kirov, Post, Que, and Yarowsky (2016)](http://www.unimorph.org/doc/Sylak-Glassman_Kirov_Post_Que_Yarowsky_2015_-_SFCM_pre-publication.pdf).

-am
